In [4]:
import pandas as pd
import numpy as np

In [5]:
jobs=pd.read_csv('fake_job_postings.csv')
jobs

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [6]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [7]:
jobs.describe(include='all')

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
count,17880.000000,17880,17534,6333,2868,14572,17879,15184,10668,17880.000000,17880.000000,17880.000000,14409,10830,9775,12977,11425,17880.000000
unique,NaN,11231,3105,1337,874,1709,14801,11967,6204,NaN,NaN,NaN,5,7,13,131,37,NaN
top,NaN,English Teacher Abroad,"GB, LND, London",Sales,0-0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,NaN,NaN,NaN,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,NaN
freq,NaN,311,718,551,142,726,379,410,726,NaN,NaN,NaN,11620,3809,5145,1734,1749,NaN
mean,8940.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042897,0.795302,0.491723,NaN,NaN,NaN,NaN,NaN,0.048434
std,5161.655742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.202631,0.403492,0.499945,NaN,NaN,NaN,NaN,NaN,0.214688
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,4470.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
50%,8940.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
75%,13410.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
max,17880.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000

In [8]:
jobs.isnull()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,True,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,True,True,False,False,False,True,False,False,False,True,True,True,True,True,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
17876,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
17877,False,False,False,True,True,False,False,False,True,False,False,False,False,True,True,True,True,False
17878,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False
17879,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False

In [9]:
jobs.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [10]:
jobs.duplicated().sum()

0

In [11]:
columns_to_drop = ["location", "department", "salary_range", "industry"]
jobs.drop(columns_to_drop, axis=1, inplace=True)
jobs

,job_id,title,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent
0,1,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Sales,0
4,5,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Sales,0
17876,17877,Payroll Accountant,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,0
17878,17879,Graphic Designer,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Design,0
17879,17880,Web Application Developers,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Engineering,0

In [12]:
# converting binary columns to boolean
b_col=['telecommuting','has_company_logo','has_questions','fraudulent']
jobs[b_col]=jobs[b_col].astype('bool')

In [13]:
jobs

,job_id,title,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent
0,1,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,False,True,False,Other,Internship,NaN,Marketing,False
1,2,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,False,True,False,Full-time,Not Applicable,NaN,Customer Service,False
2,3,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,False,True,False,NaN,NaN,NaN,NaN,False
3,4,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,False,True,False,Full-time,Mid-Senior level,Bachelor's Degree,Sales,False
4,5,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,False,True,True,Full-time,Mid-Senior level,Bachelor's Degree,Health Care Provider,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,False,True,True,Full-time,Mid-Senior level,NaN,Sales,False
17876,17877,Payroll Accountant,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,False,True,True,Full-time,Mid-Senior level,Bachelor's Degree,Accounting/Auditing,False
17877,17878,Project Cost Control Staff Engineer - Cost Con...,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,False,False,False,Full-time,NaN,NaN,NaN,False
17878,17879,Graphic Designer,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,False,False,True,Contract,Not Applicable,Professional,Design,False
17879,17880,Web Application Developers,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,False,True,True,Full-time,Mid-Senior level,NaN,Engineering,False

### Employment type

In [14]:
FULL_TIME='Full-time'
PART_TIME='Part-time'
OTHER='other'
jobs['employment_type']=jobs['employment_type'].map({
    'Full-time':FULL_TIME,
    'Part-time':PART_TIME,
    'Other':OTHER,
    'Contract':OTHER,
    'Temporary':OTHER,
})

In [15]:
jobs

,job_id,title,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent
0,1,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,False,True,False,other,Internship,NaN,Marketing,False
1,2,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,False,True,False,Full-time,Not Applicable,NaN,Customer Service,False
2,3,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,False,True,False,NaN,NaN,NaN,NaN,False
3,4,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,False,True,False,Full-time,Mid-Senior level,Bachelor's Degree,Sales,False
4,5,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,False,True,True,Full-time,Mid-Senior level,Bachelor's Degree,Health Care Provider,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,False,True,True,Full-time,Mid-Senior level,NaN,Sales,False
17876,17877,Payroll Accountant,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,False,True,True,Full-time,Mid-Senior level,Bachelor's Degree,Accounting/Auditing,False
17877,17878,Project Cost Control Staff Engineer - Cost Con...,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,False,False,False,Full-time,NaN,NaN,NaN,False
17878,17879,Graphic Designer,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,False,False,True,other,Not Applicable,Professional,Design,False
17879,17880,Web Application Developers,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,False,True,True,Full-time,Mid-Senior level,NaN,Engineering,False

### Required experience

In [16]:
JUNIOR='Junior'
STANDARD='Standard'
SENIOR='Senior'
jobs["required_experience"] = jobs["required_experience"].map({
    "Internship": JUNIOR,
    "Not Applicable": np.nan,
    "Mid-Senior level": STANDARD,
    "Associate": STANDARD,
    "Entry level": JUNIOR,
    "Executive": SENIOR,
    "Director": SENIOR
})

In [17]:
jobs

,job_id,title,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent
0,1,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,False,True,False,other,Junior,NaN,Marketing,False
1,2,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,False,True,False,Full-time,NaN,NaN,Customer Service,False
2,3,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,False,True,False,NaN,NaN,NaN,NaN,False
3,4,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,False,True,False,Full-time,Standard,Bachelor's Degree,Sales,False
4,5,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,False,True,True,Full-time,Standard,Bachelor's Degree,Health Care Provider,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,False,True,True,Full-time,Standard,NaN,Sales,False
17876,17877,Payroll Accountant,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,False,True,True,Full-time,Standard,Bachelor's Degree,Accounting/Auditing,False
17877,17878,Project Cost Control Staff Engineer - Cost Con...,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,False,False,False,Full-time,NaN,NaN,NaN,False
17878,17879,Graphic Designer,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,False,False,True,other,NaN,Professional,Design,False
17879,17880,Web Application Developers,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,False,True,True,Full-time,Standard,NaN,Engineering,False

In [18]:
print(jobs['function'].unique())

['Marketing' 'Customer Service' nan 'Sales' 'Health Care Provider'
 'Management' 'Information Technology' 'Other' 'Engineering'
 'Administrative' 'Design' 'Production' 'Education' 'Supply Chain'
 'Business Development' 'Product Management' 'Financial Analyst'
 'Consulting' 'Human Resources' 'Project Management' 'Manufacturing'
 'Public Relations' 'Strategy/Planning' 'Advertising' 'Finance'
 'General Business' 'Research' 'Accounting/Auditing' 'Art/Creative'
 'Quality Assurance' 'Data Analyst' 'Business Analyst' 'Writing/Editing'
 'Distribution' 'Science' 'Training' 'Purchasing' 'Legal']

In [19]:
print(jobs['required_education'].unique())

[nan "Bachelor's Degree" "Master's Degree" 'High School or equivalent'
 'Unspecified' 'Some College Coursework Completed' 'Vocational'
 'Certification' 'Associate Degree' 'Professional' 'Doctorate'
 'Some High School Coursework' 'Vocational - Degree'
 'Vocational - HS Diploma']

In [20]:
HIGHSCHOOL = "Highschool"
UNDERGRADUATE = "Undergraduate"
POSTGRADUATE = "Postgraduate"
Other = "Other"

jobs["required_education"] = jobs["required_education"].map({
    "Bachelor's Degree": UNDERGRADUATE, 
    "Master's Degree": POSTGRADUATE,
    'High School or equivalent': HIGHSCHOOL, 
    'Unspecified': np.nan,
    'Some College Coursework Completed': HIGHSCHOOL, 
    'Vocational': OTHER, 
    'Certification': OTHER,
    'Associate Degree': UNDERGRADUATE, 
    'Professional': OTHER, 
    'Doctorate': POSTGRADUATE,
    'Some High School Coursework': HIGHSCHOOL, 
    'Vocational - Degree': OTHER,
    'Vocational - HS Diploma': OTHER
})

In [21]:
BUSINESS = "Business"
HEALTHCARE = "Healthcare"
INFORMATION_TECHNOLOGY = "Information Technology"
ENGINEERING = "Engineering"
DESIGN = "Design"
EDUCATION = "Education"
FINANCE = "Finance"
SCIENCE = "Science"
LEGAL = "Legal"
OTHER = "Other"

jobs["function"] = jobs["function"].map({
    'Marketing': BUSINESS, 
    'Customer Service': BUSINESS, 
    'Sales': BUSINESS,
    'Health Care Provider': HEALTHCARE, 
    'Management': BUSINESS, 
    'Information Technology': INFORMATION_TECHNOLOGY,
    'Other': OTHER, 
    'Engineering': ENGINEERING, 
    'Administrative': BUSINESS, 
    'Design': DESIGN, 
    'Production': BUSINESS,
    'Education': EDUCATION, 
    'Supply Chain': BUSINESS, 
    'Business Development': BUSINESS,
    'Product Management': BUSINESS, 
    'Financial Analyst': FINANCE, 
    'Consulting': BUSINESS,
    'Human Resources': BUSINESS, 
    'Project Management': BUSINESS, 
    'Manufacturing': BUSINESS,
    'Public Relations': BUSINESS, 
    'Strategy/Planning': BUSINESS, 
    'Advertising': BUSINESS, 
    'Finance': FINANCE,
    'General Business': BUSINESS, 
    'Research': OTHER, 
    'Accounting/Auditing': FINANCE,
    'Art/Creative': DESIGN, 
    'Quality Assurance': INFORMATION_TECHNOLOGY, 
    'Data Analyst': INFORMATION_TECHNOLOGY,
    'Business Analyst': BUSINESS, 
    'Writing/Editing': DESIGN, 
    'Distribution': BUSINESS, 
    'Science': SCIENCE,
    'Training': OTHER, 
    'Purchasing': BUSINESS, 
    'Legal': LEGAL
})

In [22]:
jobs

,job_id,title,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent
0,1,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,False,True,False,other,Junior,NaN,Business,False
1,2,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,False,True,False,Full-time,NaN,NaN,Business,False
2,3,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,False,True,False,NaN,NaN,NaN,NaN,False
3,4,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,False,True,False,Full-time,Standard,Undergraduate,Business,False
4,5,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,False,True,True,Full-time,Standard,Undergraduate,Healthcare,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,False,True,True,Full-time,Standard,NaN,Business,False
17876,17877,Payroll Accountant,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,False,True,True,Full-time,Standard,Undergraduate,Finance,False
17877,17878,Project Cost Control Staff Engineer - Cost Con...,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,False,False,False,Full-time,NaN,NaN,NaN,False
17878,17879,Graphic Designer,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,False,False,True,other,NaN,other,Design,False
17879,17880,Web Application Developers,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,False,True,True,Full-time,Standard,NaN,Engineering,False

In [23]:
text_columns = ["title", "company_profile", "description", "requirements", "benefits"]
TEXT_COLUMN_NAME = "text"

jobs[TEXT_COLUMN_NAME] = jobs.loc[:, text_columns] \
    .fillna("") \
    .apply(lambda row: " ".join([row[col] for col in text_columns]), axis=1)

jobs.drop(text_columns, axis=1, inplace=True)
jobs.head()

,job_id,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent,text
0,1,False,True,False,other,Junior,NaN,Business,False,"Marketing Intern We're Food52, and we've creat..."
1,2,False,True,False,Full-time,NaN,NaN,Business,False,Customer Service - Cloud Video Production 90 S...
2,3,False,True,False,NaN,NaN,NaN,NaN,False,Commissioning Machinery Assistant (CMA) Valor ...
3,4,False,True,False,Full-time,Standard,Undergraduate,Business,False,Account Executive - Washington DC Our passion ...
4,5,False,True,True,Full-time,Standard,Undergraduate,Healthcare,False,Bill Review Manager SpotSource Solutions LLC i...

In [24]:
import string

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/rgukt123/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/rgukt123/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [25]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    cleaned_words = []
    for word in text.split():
        word_lower = word.strip(" " + string.punctuation).lower()
        if word_lower in stop_words: continue
        word_lemmatized = lemmatizer.lemmatize(word_lower)
        cleaned_words.append(word_lemmatized)
    return " ".join(cleaned_words)

jobs["text"] = jobs["text"].apply(clean_text)

In [26]:
jobs

,job_id,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,function,fraudulent,text
0,1,False,True,False,other,Junior,NaN,Business,False,marketing intern food52 created groundbreaking...
1,2,False,True,False,Full-time,NaN,NaN,Business,False,customer service cloud video production 90 se...
2,3,False,True,False,NaN,NaN,NaN,NaN,False,commissioning machinery assistant cma valor se...
3,4,False,True,False,Full-time,Standard,Undergraduate,Business,False,account executive washington dc passion impro...
4,5,False,True,True,Full-time,Standard,Undergraduate,Healthcare,False,bill review manager spotsource solution llc gl...
...,...,...,...,...,...,...,...,...,...,...
17875,17876,False,True,True,Full-time,Standard,NaN,Business,False,account director distribution vend looking aw...
17876,17877,False,True,True,Full-time,Standard,Undergraduate,Finance,False,payroll accountant weblinc e-commerce platform...
17877,17878,False,False,False,Full-time,NaN,NaN,NaN,False,project cost control staff engineer cost cont...
17878,17879,False,False,True,other,NaN,other,Design,False,graphic designer nemsia studio looking experie...
17879,17880,False,True,True,Full-time,Standard,NaN,Engineering,False,web application developer vend looking awesome...

In [27]:
jobs.to_csv("cleaned_" + 'fake_job_postings.csv')